### ISSUE TITLE
Sending SCT feedback if there is only a single request?

### ISSUE THREAD

**Issue by estark37** [ln5/draft-ietf-trans-gossip#13]
Hi all,

First, I was wondering if you are interested/open to receiving feedback on this draft via GitHub issues. :)

Second, I'm trying to find in the current draft an indication of when exactly the client should start sending the SCTs that it has observed to the server. Based on the sentence "After connecting to the HTTPS server the subsequent time, the client MUST send...", it seems that if a client only ever connects to a server once, the SCTs from that connection will never be reported back. Is that intentional?

Thanks!
Emily (Chrome security)

**Comment by ln5** [comment]
Hi Emily,

Sure. As long as we're on github, bring em on! :)

That's correct. The text is not clear at all on this point and will have to improve. The assumed attack scenario we're trying to deal with is this:
1. client connects to example.com for the first time; has no chain or SCT's for "example.com" so sends no SCT feedback; receives chain and SCT's; stores this on disk under "example.com"
2. time passes
3. client connects to example.com again but is under a MITM attack so ends up at server run by evil.com; has chain and SCT's for "exampe.com" on disk so sends that as SCT feedback (irrelevant); receives "false" chain and "false" SCT's; stores on disk under "example.com"
4. time passes, MITM ends
5. client connects to example.com again and ends up at real example.com, has "false" chain and "false" SCT's for "example.com" on disk so sends that as SCT feedback (wohoo!); receives chain and SCT's; stores on disk under "example.com"

Does this make sense?

**Comment by estark37** [comment]
Hi @ln5, thanks for the reply! Yes, that makes sense, but I guess I'm unclear on what happens if a user makes a request to example.com once and only once, and is under a MITM attack during that request. In the case where the client is a browser, should the browser later connect to example.com automatically to report the chain and SCTs, even if the user didn't initiate a second request to example.com?

**Comment by ln5** [comment]
That has not been suggested before. I'd say no because browsers acting on their own scare me. Then again I'm an easily scared browser user. @tomrittervg or @dkg might be of a different opinion.

**Comment by tomrittervg** [comment]
I'm also pretty hesitant about browsers making requests not initiated by the user.  

I will note that if the user has Proof Fetching enabled, and STH Pollination implemented, then that SCT will be resolved to a STH, and then pollinated - allowing evidence of the attack to be uncovered.  So that would cover this case... if the whole draft were implemented and the user had not disabled Proof Fetching.

**Comment by estark37** [comment]
Yeah, I agree that the browser shouldn't initiate a second request to the server on its own to report the SCTs; I wasn't sure if that's what the spec as currently written was suggesting or not.

If a browser has some sort of trusted auditor relationship, though, I think maybe it would be reasonable for the browser to periodically report SCTs to the auditor. That might be another mechanism by which this type of attack could be uncovered, in addition to STH pollination. (I'd expect a trusted auditor relationship would only exist with explicit user opt-in, in which case I find it less creepy that the browser would send a request to the auditor not explicitly initiated by the user.)

**Comment by tomrittervg** [comment]
Sure, if you have a trusted auditor, all bets are off.  In my mind, I assume stuff gets reported to the auditor every... 5 minutes(?) in a big batch, and is then probably just deleted locally.  (Also I assume the auditor connection uses pinned TLS.)

**Comment by ln5** [comment]
Tried to clarify this a bit in commit 80fb921. Please reopen if you think we need more.
